### ISSUE TITLE
folium.LayerControl()

### ISSUE THREAD

**Issue by goanes** [randyzwitch/streamlit-folium#102]
Hi 

here is my issue.

![Capture2](https://user-images.githubusercontent.com/94363317/207635568-9f0d0643-50b6-4c89-b4da-204308d75e2e.PNG)

since I add folium.LayerControl().add_to(map), the map is not showing properly and the width and heigth is not changing the display of the map. I have try on folium.Map and on st_folium

I have tried with folium_static() and it work fine

```
import streamlit as st
from streamlit_folium import st_folium
import folium
from folium.plugins import MousePosition

map = folium.Map(location=[0, 0], zoom_start=2, )
MousePosition().add_to(map)
map.add_child(folium.ClickForMarker())
folium.LayerControl().add_to(map)

st_data = st_folium(map)
```

**Comment by rafa-guedes** [comment]
I had similar problem here and opened an issue in folium https://github.com/python-visualization/folium/issues/1681 yesterday. The problem seems to have been introduced with the latest release v0.8.1. My app works ok with v0.8.0 and earlier.

**Comment by AmbroxMr** [comment]
Still having this issue in v0.10.0

**Comment by blackary** [comment]
@AmbroxMr Can you share a code snippet which shows the issue you're having?

**Comment by swdmike** [comment]
same problem here
folium                0.14.0
streamlit             1.21.0
streamlit-folium      0.11.1

m = folium.Map(location=[30.3, 120.2], zoom_start=12, tiles=None)
folium.TileLayer('openstreetmap').add_to(m)
# folium.LayerControl().add_to(m)  # if I put it here, width and heigth is not right

folium.TileLayer('Stamen Terrain').add_to(m)     

# folium.LayerControl().add_to(m)  # if I put it here, it is ok

st_folium(m, width=1300, height=800)
