### ISSUE TITLE
Possible to get a release with LayerControl fix?

### ISSUE THREAD

**Issue by kotfic** [randyzwitch/streamlit-folium#105]
Hi,  having issues with `st_folium` and `folium.LayerControl` that are apparently resolved in https://github.com/randyzwitch/streamlit-folium/pull/104 -  I was wondering if its possible to get a new release with this fix?

Thanks!

**Comment by randyzwitch** [comment]
v0.9.0 tagged just now, will take a few minutes to publish to PyPI and later today for conda-forge.
