### ISSUE TITLE
Dynamically specify required js/css

### ISSUE THREAD

**Issue by blackary** [randyzwitch/streamlit-folium#115]
Right now we load *all* of the JS and CSS related to all the supported plugins, but most of these aren't used, and it can cause issues with loading the component (e.g. #79).

**Comment by randyzwitch** [comment]
Might this actually cause more performance issues than it's worth? It's an improvement if the resource can't be reached, but if it can, it should get cached by the browser right? So it's a one-time issue, IF you can get the resource to load some time

**Comment by blackary** [comment]
Yeah, it might. I'm not even sure it's doable without a ton of work. But, folium does provide an API for getting (in order, I think) the list of js and css packages that are required for a given map, so there almost certainly is a way it could be done. I just feel bad loading tons of packages just in case, and having one that isn't actually used by anybody (from what I could tell in my github searching) cause issues like #79.

If I find a clever way to do this, maybe I'll test it out some day, but it might well cause more issues than it's worth.

**Comment by blackary** [comment]
I also wonder if it's worth packaging a pre-build version of all the JS bundled together into the source code. Would add size to the source code, but then you wouldn't have to download from any CDNs to use the component.

**Comment by randyzwitch** [comment]
That sounds better than dynamic insertionOn Feb 22, 2023, at 9:49 AM, Zachary Blackwood ***@***.***> wrote:﻿
I also wonder if it's worth packaging a pre-build version of all the JS bundled together into the source code. Would add size to the source code, but then you wouldn't have to download from any CDNs to use the component.
