### ISSUE TITLE
Style function not working when soley add to 'feature_group_to_add' parameter

### ISSUE THREAD

**Issue by KeonwooChoi** [randyzwitch/streamlit-folium#121]
Hello Im gonna using `feature_group_to_add` param rathern than add to map directly because of loading speed.

But I found that I have to add feature group to map before using `st_folium`. And it also causing slow speed. Here's my code

This code works, but slow
```
  map = folium.Map(location=[37.552213, 127.011354], zoom_start=10)
  fg = folium.FeatureGroup()
  folium.GeoJson(
            geo_json,
            style_function=lambda x:{'fillColor':'red'},
        ).add_to(fg)

  map.add_child(fg)

  out = st_folium(
      map ,
      feature_group_to_add=fg
  )
```
![image](https://user-images.githubusercontent.com/46857207/223345969-7bdb7836-ece5-4872-95a6-3c8d574b0fab.png)
---
This code not works
```
  map = folium.Map(location=[37.552213, 127.011354], zoom_start=10)
  fg = folium.FeatureGroup()
  folium.GeoJson(
            geo_json,
            style_function=lambda x:{'fillColor':'red'},
        ).add_to(fg)

  out = st_folium(
      map ,
      feature_group_to_add=fg
  )
```
![image](https://user-images.githubusercontent.com/46857207/223346103-17d19693-78d6-44d8-9c76-262edbbc0ea6.png)

**Comment by csipapicsa** [comment]
same problem in here. When I try to load the styles, it doesnt work, but when it is written there it is ok

style=LAYERSTYLE[k]

ma.m2.add_child(layers[k].add_child(folium.GeoJson(data=files[k], style_function=lambda x: style)))   # every layer has an default orange color

ma.m2.add_child(layers[k].add_child(folium.GeoJson(data=files[k], style_function=lambda x:{"fillColor": "green"}))) # this is works.

Even I get "make this notebook trusted" message

**Comment by TaylerUva** [comment]
I am having the same issue. It's a deal breaker for if I'm able to use streamlit or not

**Comment by BastienGauthier** [comment]
Same here, which prevent me from using Choropleth. 

Use case : I was hoping that the "feature_group_to_add" could help me with Choropleth updates given a slider.

**Comment by patrontheo** [comment]
Hey, @KeonwooChoi, @csipapicsa, @TaylerUva, @BastienGauthier  This has been solved in the latest PR. (see #146 )
