### ISSUE TITLE
No radius data for circles in output

### ISSUE THREAD

**Issue by nsight1** [randyzwitch/streamlit-folium#123]
related to this:  https://github.com/Leaflet/Leaflet.draw/issues/390
when drawing a circle, the data returned is as a point.
```
"all_drawings": [
	0: {
		"type": "Feature"
		"properties": {}
		"geometry": {
			"type": "Point"
			"coordinates": [
				0: -104.853516
				1: 45.261355
			]
		}
	}
]
```
Need to add a workaround to the frontend code to capture circle radius as a property.

**Comment by randyzwitch** [comment]
In current versions of the package, a field called "last_circle_radius" provides this information in kilometers.

No circle:
<img width="1287" alt="Screenshot 2023-05-24 at 1 26 00 PM" src="https://github.com/randyzwitch/streamlit-folium/assets/2762787/a85ad215-5ef4-410f-9ed1-009002bf1010">

Drawn circle:
<img width="1062" alt="Screenshot 2023-05-24 at 1 27 21 PM" src="https://github.com/randyzwitch/streamlit-folium/assets/2762787/efb612f9-59c9-4d1e-bf63-b5e18f9545b4">

**Comment by nsight1** [comment]
Hi, thanks for the swift reply but this does not solve the problem:
1. when you export the draw data, there is no radius for circles (just the center points) so there is no way to rebuild the data.
2. if I draw multiple circles on my map there is no way to calculate the total area covered by all circles.
3. if i add multiple circles, but then delete a few of the circles, there is no way to know which circle the last_cirlce_radius value corresponds to

The link i provided has many work arounds for example adding the radius as a property to each item in the `all_drawings` list would work. The items already have an empty `properties` key than can be used as per this example:
```
if (type === "circle") {
       var radius = layer.getRadius();
       geoJSON.properties.radius = radius;
}
```

**Comment by randyzwitch** [comment]
Just to clarify, when you say "export the draw data", what are you referring to? Via Python/Streamlit or the browser?

**Comment by nsight1** [comment]
If you click on the "Export" hyperlink below your map as per your screenshot above.

**Comment by randyzwitch** [comment]
I see...this is one of those real edge type cases. We're relying on Folium for that export link functionality, and Folium relies on Leaflet (obviously). So it really would be better if Leaflet did it.

I'll leave this open, as if someone put the time in to patch this here I think we'd merge it (not sure what @blackary thinks), but I can't commit to patching upstream dependencies as part of the scope of this package.

**Comment by randyzwitch** [comment]
Our build file shows the basic steps:

https://github.com/randyzwitch/streamlit-folium/blob/master/.github/workflows/run_tests_each_PR.yml#L28

**Comment by nsight1** [comment]
fixed this in my PR: https://github.com/randyzwitch/streamlit-folium/pull/124
