### ISSUE TITLE
Upgrade node versions in build scripts

### ISSUE THREAD

**Issue by randyzwitch** [randyzwitch/streamlit-folium#127]
When trying to publish to PyPI using automatic GitHub Action, upload fails with following message:

`error:0308010C:digital envelope routines::unsupported`

#126 "fixes" this by pinning node version as a temporary patch, but should properly fix this using https://stackoverflow.com/a/73027407

**Comment by BastienGauthier** [comment]
I made a proposition in a PR for this, but I think the tests are failing due to https://github.com/randyzwitch/streamlit-folium/issues/148
Should I correct the requirements.txt or wait for a correction of the compatibility & rebase ?
