### ISSUE TITLE
Make available with anaconda (conda - forge)

### ISSUE THREAD

**Issue by saguerraty** [randyzwitch/streamlit-folium#13]
Hi there, this is more of a request than an issue, but would it be possible for this package to be made available through conda forge?
[conda forge anaconda channel](https://conda-forge.org/#page-top)
:)

**Comment by randyzwitch** [comment]
Seems completely reasonable to me. If someone were so inclined, they could submit the package to conda-forge and add me as a maintainer :)

**Comment by randyzwitch** [comment]
Wasn't actually that hard, so this is underway

https://github.com/conda-forge/staged-recipes/pull/13891

**Comment by randyzwitch** [comment]
Just to be clear, it’s in progress, something is wrong with the recipe. But I’ll try and get this done when I’m back at work on Monday

**Comment by randyzwitch** [comment]
This got merged to master, so once it's done building you'll be able to run

`conda install -c conda-forge streamlit-folium`
