### ISSUE TITLE
Add code for other pages in https://folium.streamlit.app/ 

### ISSUE THREAD

**Issue by michaelbilow** [randyzwitch/streamlit-folium#138]
Would you be willing to add the code for the pages under https://folium.streamlit.app/ into this repo? I'm having trouble with how to initialize `st.session.state["markers"]` on [this page](https://folium.streamlit.app/dynamic_map_vs_rerender), or what the button's callback looks like, and that part of the code isn't visible on that page.

Many thanks.

**Comment by randyzwitch** [comment]
All of the code for the demo app is present in this repo. Per the page you reference:

https://github.com/randyzwitch/streamlit-folium/blob/master/examples/pages/dynamic_map_vs_rerender.py

So take a look at the /examples/pages directory and you should see everything you need.
