### ISSUE TITLE
Backdated Folium Version

### ISSUE THREAD

**Issue by hridoyboss12** [randyzwitch/streamlit-folium#14]
While I installed streamlit-folium, I noticed that it uninstalled my existing folium module version = 0.12.1 and reinstall folium version = 0.11.0
Then I searched in your github and found in the setup.py file
`install_requires=["streamlit>=0.63", "folium==0.11"]`
My question is, is it necessary to use folium version 0.11.0? Or Can you set the code
`install_requires=["streamlit>=0.63", "folium>=0.11"]`
By the way,
Thank you so much for the hard work you have done. This module helps a lot.

**Comment by randyzwitch** [comment]
Nope, nothing specific about 0.11 other than it was the newest one at the time I developed it. Can you submit a pull request for this?

**Comment by randyzwitch** [comment]
Version 0.2.0 of streamlit-folium is now on PyPI, so this should be resolved. If there are any issues, please comment here and we can re-open
