### ISSUE TITLE
Marker popup not working in Safari

### ISSUE THREAD

**Issue by espogian** [randyzwitch/streamlit-folium#140]
Hi, using streamlit_folium 0.13 and Safari 16.6, I'm unable to show the content of a marker popup on the map. The issue is easily reproducible by clicking on the markers in this demo page: https://folium.streamlit.app/simple_popup

**Comment by espogian** [comment]
I want also to add the the issue is *not* present with the plain folium library: https://python-visualization.github.io/folium/quickstart.html

**Comment by randyzwitch** [comment]
Can you see if there is any messages in the developer tab in Safari to hint at what the issue might be? It's working in Chrome, so hopefully Safari will tell us what it doesn't like

**Comment by randyzwitch** [comment]
Looks like this might be a duplicate to #61

**Comment by espogian** [comment]
I do not see any relevant in Safari logs apparently. The reason why I've opened another issue is that #61 mentions that the issue is not occurring using an inline explicit popup, while for me this is not working. Oddly enough, the issue seems to be present for simple (marker) popups only, for example GeoJson popups are working: https://folium.streamlit.app/geojson_popup

**Comment by randyzwitch** [comment]
Closing, as I'm guessing/hoping that 0.20.0 fixes this by including all the relevant JS libraries. If that is not the case, please let me know and I'll re-open this issue
