### ISSUE TITLE
GroupedLayerControl breaks st_folium

### ISSUE THREAD

**Issue by fcusimano** [randyzwitch/streamlit-folium#150]
When using `folium.plugins.GroupedLayerControl`, my map looks like this:
![image](https://github.com/randyzwitch/streamlit-folium/assets/36202236/fab3fd22-8f36-4abd-b2e7-1dc61f33e278)

When I use `folium.LayerControl`, it looks like this:
![image](https://github.com/randyzwitch/streamlit-folium/assets/36202236/f4d60778-d4ff-427d-ba5b-f2a24aedbbea)

Code example: 
```py
m = folium.Map(
    location=[city.dissolve().centroid.y, city.dissolve().centroid.x],
    tiles="cartodbpositron",
    zoom_start=11,
)

folium.GeoJson(
    city,
    style_function=lambda x: {"color": "black", "fill": None, "weight": 0.5},
    control=False,
).add_to(m)

transit_layer = folium.GeoJson(
      geo_data_dict["transit"].data_per_point,
      style_function=lambda x: {"color": "red"},
      control=True,
      name="transit",
      show=False,
  ).add_to(m)

GroupedLayerControl({"Per point": [transit_layer]}).add_to(m)
# folium.LayerControl(collapsed=False).add_to(m)

st_folium(
        m,
        use_container_width=True,
    )
```

A similar issue has been mentioned in https://github.com/randyzwitch/streamlit-folium/issues/139 but the discussion focused more on `SideBySideLayers`

**Comment by BastienGauthier** [comment]
For information, I used to have this error when I used a marker with the same name multiple times, working with folium_static but not st_folium.
