### ISSUE TITLE
Dynamically updating center and zoom of the map does not work properly

### ISSUE THREAD

**Issue by patrontheo** [randyzwitch/streamlit-folium#154]
Hello,

A weird issue appears when the user interact with the map and we want to then move the map to a specific location.

Here is some sample code to reproduce the bug:
```python
import folium
import geopandas as gpd
import shapely
import streamlit as st

from streamlit_folium import st_folium

START_LOCATION = [37.7934347109497, -122.399077892527]
START_ZOOM = 17

if not 'map_center' in st.session_state:
    st.session_state['map_center'] = START_LOCATION
if not 'map_zoom' in st.session_state:
    st.session_state['map_zoom'] = START_ZOOM

def move_map(coord, zoom):
    st.session_state['map_center'] = coord
    st.session_state['map_zoom'] = zoom

coord1 = [37.7934347109497, -122.399077892527]
zoom1 = 17.01
marker1 = folium.Marker(location=coord1)

coord2 = [37.7937070646238, -122.43]
zoom2 = 17.02
marker2 = folium.Marker(location=coord2)

st.button("go to marker right", on_click=move_map, args=(coord1, zoom1,))
st.button("go to marker left", on_click=move_map, args=(coord2, zoom2, ))

map = folium.Map(
    location=START_LOCATION, zoom_start=START_ZOOM, tiles="OpenStreetMap", max_zoom=21
)
marker1.add_to(map)
marker2.add_to(map)

st_folium(
    map,
    width=800,
    center=st.session_state['map_center'],
    zoom=st.session_state['map_zoom'],
    height=450,
    debug=True,
)
```

On this app, if you click on `go to marker left`, then `go to marker right`, and so on, without interacting with the map, then it work as expected.
Now, if you:
- Load the app
- Click on `go to marker left`
- interact with the map (change a bit the center AND change the zoom)
- Click on `go to marker right`
- It will __not__ take you to the right place

Do you have any idea in mind why it would do behave like that ? @blackary 
Thanks a lot

**Comment by patrontheo** [comment]
@randyzwitch Any pointers to where I could have a look, and maybe try to do a PR ? (not sure I have the required skills though)

**Comment by patrontheo** [comment]
Hey @randyzwitch @blackary,

I spotted this https://github.com/vue-leaflet/Vue2Leaflet/issues/170#issuecomment-389442828
It says that "The second call to setView (setting the center) seems to be ignored if the zoom change is still ongoing."

It could be what's happening in [index.tsx: line268](https://github.com/randyzwitch/streamlit-folium/blob/abb655e9e96ed77b5f65fb5cec29b9ba35f0e501/streamlit_folium/frontend/src/index.tsx#L268C9-L268C9), where the zoom is changed and then the center.

The solution they use is to use a single call to `setView` method, specifying the center and the zoom.

I'm not sure how to build the frontend after modifying it, so I don't know how to test this.

Maybe you could give it a shot ?

Thanks a lot

**Comment by blackary** [comment]
@patrontheo This is somewhat of a common issue with streamlit widgets that have some state (e.g. st.multiselect).
1. The first time you set them up, they use whatever defaults you pass in.
2. If you update those defaults, and don't interact with the widget, the widget gets updated
3. However, if you interact with the widget, it keeps the state from your manual interactions, and don't auto-update if you change the defaults

This is reasonable a lot of the time, because once people have changed a thing, they generally don't want it to go back to the defaults, even if the default values change. But, it can be problematic for cases like this.

The general solution, if you don't want number 3 to happen, is to change the `key` of the widget, so that it forces streamlit to re-create the widget with the new defaults. You can do that like this:

```python
import folium
import streamlit as st

from streamlit_folium import st_folium

START_LOCATION = [37.7934347109497, -122.399077892527]
START_ZOOM = 17

if "map_center" not in st.session_state:
    st.session_state["map_center"] = START_LOCATION
if "map_zoom" not in st.session_state:
    st.session_state["map_zoom"] = START_ZOOM
if "map_key" not in st.session_state:
    st.session_state["map_key"] = 0


def move_map(coord, zoom):
    st.session_state["map_center"] = coord
    st.session_state["map_zoom"] = zoom
    st.session_state["map_key"] += 1


coord1 = [37.7934347109497, -122.399077892527]
zoom1 = 17.01
marker1 = folium.Marker(location=coord1)

coord2 = [37.7937070646238, -122.43]
zoom2 = 17.02
marker2 = folium.Marker(location=coord2)

st.button(
    "go to marker right",
    on_click=move_map,
    args=(
        coord1,
        zoom1,
    ),
)
st.button(
    "go to marker left",
    on_click=move_map,
    args=(
        coord2,
        zoom2,
    ),
)

map = folium.Map(
    location=START_LOCATION, zoom_start=START_ZOOM, tiles="OpenStreetMap", max_zoom=21
)
marker1.add_to(map)
marker2.add_to(map)

st_folium(
    map,
    width=800,
    center=st.session_state["map_center"],
    zoom=st.session_state["map_zoom"],
    height=450,
    debug=True,
    key=st.session_state["map_key"],
)
```

**Comment by patrontheo** [comment]
@blackary Aah I see, I though that changing the defaults would update the widget anyway, even if user interacted with it.

Thanks a lot mate!

**Comment by patrontheo** [comment]
@blackary can you reopen this (I opened PR #168) ?
I think I fixed the issue with a better solution.

**Comment by randyzwitch** [comment]
This doesn't need to be re-opened, your PR is plenty of documentation about the intent
