### ISSUE TITLE
Plot not rendering correctly when using `m.keep_in_front()`

### ISSUE THREAD

**Issue by this-josh** [randyzwitch/streamlit-folium#155]
I have some circle markers which I'd like to keep in front, but this doesn't render correctly in streamlit.

```python
import folium
from streamlit_folium import st_folium

m = folium.Map()
markers = []
markers.append(folium.CircleMarker(
    location=[0, 0],
))
markers.append(folium.CircleMarker(
    location=[10, 0.000000001],
    color='red',
))

_ = [marker.add_to(m) for marker in markers]
_ = m.keep_in_front(*markers[:1]) # can use this or the line below, both give the same issue
# m.keep_in_front(*markers[:1])

m.save('map.html')

st_data = st_folium(m)
```

When viewing the saved files, without the `keep_in_front` the red circle is on top, but when we use `keep_in_front` we get blue on top. 

**Streamlit screenshots**

Without `keep_in_front`:
<img width="533" alt="image" src="https://github.com/randyzwitch/streamlit-folium/assets/59419126/8d050123-d497-484b-b7f1-fb9fddc4bf86">

With `keep_in_front`: (the image shows all that is rendered)

Here we expect the blue circle to be in front. 

<img width="547" alt="image" src="https://github.com/randyzwitch/streamlit-folium/assets/59419126/0889d4f6-0a2a-4dc6-973d-e905f95ae0a6">

python:3.12.0 and 3.11.6
folium:0.14.0
streamlit-folium:0.16.0

full `poetry.lock` is [in this gist](https://gist.github.com/this-josh/afe60ee8ab8df97a3c7ce55f66185d36)

**Comment by this-josh** [comment]
This is all that gets added to the `Main Map Leaflet.js`

```javascript
function objects_in_front() {
        circle_marker_div_1.bringToFront();
};
map_div.on("overlayadd", objects_in_front);
$(document).ready(objects_in_front);

```

**Comment by randyzwitch** [comment]
I would guess you'd need to add jquery to this file... @blackary would know better than me:

https://github.com/randyzwitch/streamlit-folium/blob/master/streamlit_folium/frontend/package.json

**Comment by randyzwitch** [comment]
nvm...looks like we already have jquery, just not version 3+

https://github.com/randyzwitch/streamlit-folium/blob/master/streamlit_folium/frontend/public/index.html#L15

Feels like we should be able to clean that up pretty easily, adding v1, v2 and then additionally v3 of jquery doesn't seem correct.

**Comment by this-josh** [comment]
Hi @randyzwitch,

Thank you for looking into this

I have tried 
https://github.com/randyzwitch/streamlit-folium/blob/16016bee2968474981f3c781ef4fdfa77f19f3ed/streamlit_folium/__init__.py#L253

adding `html+='<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>n'` I presume this is equivalent to adding it to the `index.html`?

**Comment by randyzwitch** [comment]
I would guess that you can't inject javascript via Python and have it load due to security issues.

**Comment by blackary** [comment]
@this-josh Since the documentation explicitly says that keep_in_front doesn't work for markers, I don't think this is a streamlit-folium bug at all. 

https://python-visualization.github.io/folium/latest/reference.html#folium.folium.Map.keep_in_front

> Does not work with markers, for those use z_index_offset.

If you change your code add a z_index_offset, it seems to work fine
```python
markers.append(
    folium.CircleMarker(
        location=[10, 0.000000001],
        color="red",
        z_index_offset=1000000,
    )
)
```

**Comment by this-josh** [comment]
You're right it says it's not supported but it does work - see MWE above. Thanks for your suggestion, I also intend to use feature groups which I can reproduce the error with. Given that folium can render the plot correctly with `m.save` and streamlit_folium cannot it would seem to be an error with `streamlit_folium`

```python
fg1 = folium.FeatureGroup(name="Plot1")
markers[0].add_to(fg1)
fm.keep_in_front(fg1) 
fg2 = folium.FeatureGroup(name="Plot2")
markers[1].add_to(fg2)

fg = folium.FeatureGroup(name="Markers")
[fg.add_child(f) for f in (fg1,fg2)]

# choose which you want to demo
streamlit = True
if streamlit:
    st_data = st_folium(fm, key="1", debug=True,returned_objects=[], feature_group_to_add=fg)
else:
    fm.add_child(fg)
    fm.save('map1.html')
```
Perhaps #157 may help

**Comment by this-josh** [comment]
@blackary Incidentally, I am not finding `z_index_offset` or `z_index` to have any impact on folium, and there is only one mention of them in their [docs](https://python-visualization.github.io/folium/latest/search.html?q=z_index_offset) which is the link you attached above. I'll open an issue there as well.

> However, I still believe there is a `streamlit_folium` bug in not working with `keep_in_front` and feature groups.

**Comment by blackary** [comment]
@this-josh The example you gave with feature groups works if you add the feature groups to the map directly 
```python
import folium

from streamlit_folium import st_folium

fm = folium.Map()

markers = []
markers.append(
    folium.CircleMarker(
        location=[0, 0],
    )
)
markers.append(
    folium.CircleMarker(
        location=[10, 0.000000001],
        color="red",
    )
)

fg1 = folium.FeatureGroup(name="Plot1")
markers[0].add_to(fg1)
fm.keep_in_front(fg1)
fg2 = folium.FeatureGroup(name="Plot2")
markers[1].add_to(fg2)

fg = folium.FeatureGroup(name="Markers")
[fg.add_child(f) for f in (fg1, fg2)]
fg.add_to(fm)

st_folium(fm, key="1", debug=True, returned_objects=[])
```
This results in the blue circle being on top 
<img width="269" alt="image" src="https://github.com/randyzwitch/streamlit-folium/assets/4040678/3e6228ea-0f66-4249-9d47-8af3c06387a7">

**Comment by this-josh** [comment]
@blackary Thank you for your suggestion, this works on your recent `0.17.0` release but not `0.16.0` (which this issue was made on so this can be closed now as the `streamlit_folium` bug has been fixed. 

Incidentally the code in my first post now works. Thank you @randyzwitch for the `jquery` fix.
