### ISSUE TITLE
Draw example doesn't work with `folium = ^0.15.0`

### ISSUE THREAD

**Issue by this-josh** [randyzwitch/streamlit-folium#161]
Sorry I know I've raised a lot of tickets recently, I just believe it's good to raise them when found. 

The draw example from your docs (they seem to be down currently so cannot link them)
```python 
import folium
import streamlit as st
from folium.plugins import Draw

from streamlit_folium import st_folium

m = folium.Map(location=[39.949610, -75.150282], zoom_start=5)
Draw(export=True).add_to(m)

c1, c2 = st.columns(2)
with c1:
    output = st_folium(m, width=700, height=500)

with c2:
    st.write(output)
```

Doesn't work with ^0.15.0 (I am using `0.15.1` specifically. 

After placing a marker it dones't deselect the tool, and the markers location is not updated in the output:
![image](https://github.com/randyzwitch/streamlit-folium/assets/59419126/3502f8cd-f166-4ba2-98e8-c546cde9181b)

Versions
```
folium                    0.15.1
streamlit                 1.29.0
streamlit-folium          0.17.2
```

Thanks,
Josh

**Comment by this-josh** [comment]
FYI this is [https://folium.streamlit.app/](https://folium.streamlit.app/) currently

![image](https://github.com/randyzwitch/streamlit-folium/assets/59419126/b82d827a-d6f1-41aa-8730-c03c70c7b32c)

**Comment by this-josh** [comment]
By the way I've seen that you don't support `0.15.0`, note your `requirements.txt`  doesn't exclude `0.15.1` which might be your desired scenario.

If you don't want to support `0.15.x` change this `folium>=0.13,!=0.15.0 ` to  `folium>=0.13,<0.15.0`

https://github.com/randyzwitch/streamlit-folium/blob/abb655e9e96ed77b5f65fb5cec29b9ba35f0e501/requirements.txt#L2

**Comment by randyzwitch** [comment]
> By the way I've seen that you don't support 0.15.0, note your requirements.txt doesn't exclude 0.15.1 which might be your desired scenario.

No, that is the intended scenario. 0.15.0 of Folium made a change to its internals, which broke this package. 0.15.1 of Folium made a change that was intended to fix it, so we intended to support just that patch version and going forward.

However, the Folium change may have broken more than we expect, which might be what you are seeing with this functionality.

**Comment by blackary** [comment]
I'm not seeing that behavior on the draw page -- it seems to be working fine
<img width="1265" alt="image" src="https://github.com/randyzwitch/streamlit-folium/assets/4040678/9d9b07a9-677d-4bc1-aab8-ddb1acd0c369">

**Comment by this-josh** [comment]
Hm? Are you using a clean env with the same versions as I mentioned above?

I've recreated my env and still experience the issue on both Chrome and Safari

**Comment by patrontheo** [comment]
I also had a issues with the draw plugin and latest version of each packages (when drawing squares).
I downgraded to folium 0.14 and streamlit-folium 0.16 and it works.

**Comment by this-josh** [comment]
Interestingly the export button exports the correct data

**Comment by blackary** [comment]
Sorry about that @this-josh, I thought you meant that the drawing example was broken on https://folium.streamlit.app, which is what I was testing.

#162 should resolve this issue

**Comment by this-josh** [comment]
Are you on streamlit_folium 0.17.4? This should be fixed.
