### ISSUE TITLE
 Difference icon_type between folium and st_folium

### ISSUE THREAD

**Issue by duanra08** [randyzwitch/streamlit-folium#170]
Hello,
I have a rendering issue between Folium and st_folium.
Indeed, st_folium doesn’t display the numbers in my bubbles. With Folium, I use the icons fa-1, fa-2,…
And when I use st_folium, the numbers in the markers disappear.

![folium or st_folium](https://github.com/randyzwitch/streamlit-folium/assets/114295224/cafb707f-c155-4717-97e4-a129f3200da4)

code:
```
import streamlit as st
import folium
from folium.map import Icon
from streamlit_folium import st_folium

st.set_page_config(layout='wide')

m = folium.Map(location=[39.949610, -75.13282], zoom_start=14, height=500)

icons_list = ["1", "2", "3", "star", "heart"]

for i, icon in enumerate(icons_list):
    folium.Marker(
        [39.949610, -75.150282 + i/100],
        icon=Icon(icon=icon, prefix='fa', color='red', icon_color='white')
    ).add_to(m)


cols = st.columns(2)

with cols[0]:
    "## Using `components.html`"
    st.components.v1.html(
        m.get_root()._repr_html_(), height=500,
    )

with cols[1]:
    "## Using `st_folium`"
    st_folium(m, returned_objects=[], use_container_width=True, height=500)
```

Thank you to edsaac from discuss.streamlit.io for the code and the picture

**Comment by randyzwitch** [comment]
I suspect this might be resolved with our newest release, as we've improved how the various required libraries for folium are loaded. Please let us know if this is still an issue

**Comment by randyzwitch** [comment]
Closing this, as I would guess the newest version of the package solves this issue. If not, happy to re-open
