### ISSUE TITLE
Draw plugin is broken

### ISSUE THREAD

**Issue by hansthen** [randyzwitch/streamlit-folium#178]
Notwithstanding that #161 is closed, the Draw plugin still seems broken. For instance, if you try to finalize a Polygon shape by clicking on the first drawn vertex the Polygon is not closed, and the dotted line from the previous vertex stays visible.

The same happens for rectangle shapes, releasing the mouse button will not finalize the shape. In the console, I see the following error message:
```
index.tsx:137 Uncaught TypeError: Cannot read properties of undefined (reading 'toGeoJSON')
    at onLayerClick (index.tsx:137:25)
    at i.onDraw (index.tsx:108:10)
    at i.fire (Events.js:190:11)
    at i._fireCreatedEvent (leaflet.draw.js:8:3599)
    at i._fireCreatedEvent (leaflet.draw.js:8:13742)
    at i._finishShape (leaflet.draw.js:8:7335)
    at i._endPoint (leaflet.draw.js:8:8689)
    at i._onTouch (leaflet.draw.js:8:9099)
    at i.fire (Events.js:190:11)
    at i._touchEvent (VM3038 leaflet.draw.js:9:8968)
onLayerClick @ index.tsx:137
onDraw @ index.tsx:108
fire @ Events.js:190
_fireCreatedEvent @ leaflet.draw.js:8
_fireCreatedEvent @ leaflet.draw.js:8
_finishShape @ leaflet.draw.js:8
_endPoint @ leaflet.draw.js:8
_onTouch @ leaflet.draw.js:8
fire @ Events.js:190
_touchEvent @ VM3038 leaflet.draw.js:9
_onTouchStart @ VM3038 leaflet.draw.js:9
c @ DomEvent.js:92
Ut @ DomEvent.Pointer.js:98
(anonymous) @ DomEvent.Pointer.js:59
```

I tested this with the following versions
```
streamlit==1.33.0
folium==0.16.0
streamlit_folium==0.19.0
```

**Comment by randyzwitch** [comment]
Is this still an issue with the version just released that contains your dynamic library changes?

**Comment by hansthen** [comment]
Probably not, because I think it was included in the automated tests. I will check to verify.

**Comment by hansthen** [comment]
It seems to work fine. The only issue I could see was that the Export link is displayed twice. Shall I create a new issue for that?

![streamlit-folium-documentation-Draw-Support](https://github.com/randyzwitch/streamlit-folium/assets/2202342/f056ba98-2d3a-4f77-8254-89a4931b8c66)

**Comment by blackary** [comment]
@hansthen Yes please, if you could create a new issue for the duplicated Export, that would be great
