### ISSUE TITLE
Colormap not showing in map

### ISSUE THREAD

**Issue by ajkoch** [randyzwitch/streamlit-folium#190]
Hi,

Recently I noticed that my colormap legend had dissapeared from the map. It was after I reinstalled my environment I use to run the webapp. 

I also noticed that the colormap legend dissapeared from the example in 'geojson popup'. In the code there is still this line:
`colormap.add_to(m)`

But in the app itself, it is not showing anymore. Could there be some bug?

**Comment by ajkoch** [comment]
I can confirm that the colormap still shows in version 0.19.1

**Comment by randyzwitch** [comment]
Wonder if this too is related to #181

**Comment by randyzwitch** [comment]
I would guess this is fixed by #193
