### ISSUE TITLE
ModuleNotFoundError: No module named 'streamlit.components'; 'streamlit' is not a package

### ISSUE THREAD

**Issue by LZY-SPCA** [randyzwitch/streamlit-folium#216]
I want to run the example in https://folium.streamlit.app/ but encountered ModuleNotFoundError: No module named 'streamlit.components'; 'streamlit' is not a package. I have installed steamlit and steamlit-folium.
`import streamlit as st`
`from streamlit_folium import st_folium`
python version: 3.11.9

**Comment by randyzwitch** [comment]
How are you trying to run the example? Did you make a fork of this repo, are you copying the code in...something else?

**Comment by LZY-SPCA** [comment]
`import folium
import streamlit as st

from streamlit_folium import st_folium

m = folium.Map(location=[39.949610, -75.150282], zoom_start=16)
folium.Marker(
    [39.949610, -75.150282], popup="Liberty Bell", tooltip="Liberty Bell"
).add_to(m)

st_data = st_folium(m, width=725)`
just copy the code into PyCharm and install the packages.

**Comment by LZY-SPCA** [comment]
Well, I could run it in another pc so maybe I could find the problem by myself. Thanks!
