### ISSUE TITLE
Could I get the coordinates of the map without running as a service?

### ISSUE THREAD

**Issue by LZY-SPCA** [randyzwitch/streamlit-folium#218]
I used `fit_bounds()` in folium to focus a specific place but folium doesn't inform me the new corner coordinates of the canvas map. I need to use the coordinates to crop a rectangle area. Can I just call a function or api to get them without launching a service?

**Comment by randyzwitch** [comment]
This package is almost exclusively for the display of Folium maps within Streamlit. The package only does two things: displays a map and optionally returns data about the map back to Streamlit. Any actual interaction with the Folium/leaflet.js packages is handled outside of this package.
