### ISSUE TITLE
streamlit-folium: release button not working

### ISSUE THREAD

**Issue by gomesdaciel** [randyzwitch/streamlit-folium#227]
I'm trying to implement this code:

```
import folium
import streamlit as st

from folium.plugins import Draw
from streamlit_folium import st_folium

m = folium.Map(location=[43.72299, 10.396579], zoom_start=13)
Draw(export=True).add_to(m)

folium.Marker(
    location=[43.72299, 10.396579],
    popup="Torre di Pisa"
).add_to(m)

c1, c2 = st.columns(2)
with c1:
    output = st_folium(m, use_container_width=True)

with c2:
    st.write(output)  
```

But after clicking on the marker and trying to draw a shape, it seems that the mouse gets stuck, just like what is described here: [Streamlit_folium release button not working](https://discuss.streamlit.io/t/streamlit-folium-release-button-not-working/61894).

Do you guys have any idea how to solve this problem?

**Debug info:**
```
folium==0.17.0
streamlit==1.38.0
streamlit_folium==0.22.1
```

**Comment by blackary** [comment]
Is this different from the behavior you see on https://folium.streamlit.app/draw_support?

**Comment by randyzwitch** [comment]
Closing, as everything seems to be working as expected based on the demo
