### ISSUE TITLE
Build more impressive example

### ISSUE THREAD

**Issue by randyzwitch** [randyzwitch/streamlit-folium#3]
To really reinforce how streamlit-folium works, it'd be great to have a more robust example. Something that shows advanced functionality from Folium, integration of Streamlit widgets to control the output, etc.

https://github.com/randyzwitch/streamlit-folium/blob/master/examples/streamlit_folium_example.py

**Comment by juancalvof** [comment]
This example may help: https://github.com/randyzwitch/streamlit-folium/issues/4

**Comment by juancalvof** [comment]
https://github.com/randyzwitch/streamlit-folium/pull/5

**Comment by giswqs** [comment]
I just created some examples using leafmap. Check this out: https://share.streamlit.io/giswqs/leafmap-streamlit/app.py

**Comment by randyzwitch** [comment]
Hi @giswqs - 

I'm not sure I'm understanding, since leafmap is a different library? Or are you offering to make these same examples but in Folium?

Best,
Randy

**Comment by giswqs** [comment]
Leafmap has multiple plotting backends, including folium, ipyleaflet, heremap, and kepler.gl. Most streamlit examples I posted use the folium plotting backends, so they are certainly applicable to streamlit-folium. Leafmap simply makes it easier to use folium. You can achieve the same thing by folium only but many more lines of code.
