### ISSUE TITLE
Get zoom level

### ISSUE THREAD

**Issue by giswqs** [randyzwitch/streamlit-folium#38]
Is it possible to get the zoom level of a map object? I saw a similar question at https://github.com/python-visualization/folium/issues/1352, but there is no solution.

**Comment by bartboogmans** [comment]
map1.getZoom() gives me nothing

The leaflet class itself (which I believe is the superclass) does however show it in its documentation:
https://leafletjs.com/reference-1.6.0.html#map

```
>> zoomlevel = self.map1.getZoom()

Map' object has no attribute 'getZoom'
```

**Comment by blackary** [comment]
@bartboogmans 

If you add your map to the streamlit app with `output = st_folium(self.map1)`, then `output` becomes a dictionary that has, among other things, a `"zoom"` key, so `output["zoom"]` will give you the current zoom-level of the map.

**Comment by bartboogmans** [comment]
The st_folium function seems to be designed for Streamlit apps, that not everybody might use (including me). 

Such a dictionary would do the job though, so thats a good idea. 
Any idea if/how one could access this dictionary in non streamlit apps?

**Comment by randyzwitch** [comment]
This package is specifically designed to work in Streamlit, that's its complete scope. Broadening to make this available in other packages would require some sort of plugin specification between various web app projects, which does not currently exist.

**Comment by bartboogmans** [comment]
Whoops, I did not see that it was specifically for the combination with streamlit. I thought it was a general topic, so  you're right to point this out.
