### ISSUE TITLE
Caching Folium Maps

### ISSUE THREAD

**Issue by juancalvof** [randyzwitch/streamlit-folium#4]
Hello everyone!

In the meanwhile, that we start making a bidirectional component with javascript, I was wondering how caching Folium Maps. 

I have created this example for the purpose of it:

```
import streamlit as st
import folium
import pandas as pd
import streamlit.components.v1 as components
import numpy as np

def create_test_df():
    data = {"id": range(10000),
            "year": np.random.choice(range(2018, 2021), 10000),
            "type": np.random.choice(["type_a", "type_b", "type_c"], 10000),
            "latitude": np.random.uniform(low=10, high=20, size=10000),
            "longitude": np.random.uniform(low=10, high=20, size=10000)}

    # Respects order
    return pd.DataFrame(data, columns=["id", "year", "type", "latitude", "longitude"])


def _plot_dot(point, map_element, color_col, radius=4, weight=1, color='black'):
    color_dict = {2018: "blue", 2019: "orange", 2020: "red"}

    folium.CircleMarker(location=[point["latitude"], point["longitude"]], radius=radius, weight=weight,
                        color=color, fill=True,
                        fill_color=color_dict[point[color_col]],
                        fill_opacity=0.9,
                        tooltip=f'<b>id: </b>{str(point["id"])}'
                                f'<br></br>'f'<b>year: </b>{str(point["year"])}'
                                f'<br></br>'f'<b>type: </b>{str(point["type"])}',
                        popup=f'<b>id: </b>{str(point["id"])}'
                              f'<br></br>'f'<b>year: </b>{str(point["year"])}'
                              f'<br></br>'f'<b>type: </b>{str(point["type"])}'
                        ).add_to(map_element)


def generate_map(df):
    map_element = folium.Map(location=[15, 15], zoom_start=6, tiles='cartodbpositron')

    df.apply(_plot_dot, axis=1, args=[map_element, "year"])

    return map_element


def folium_static(fig, width=700, height=500):
    if isinstance(fig, folium.Map):
        fig = folium.Figure().add_child(fig)

    return components.html(fig.render(), height=(fig.height or height) + 10, width=width)


if __name__ == "__main__":
    st.title("Caching Folium Maps")

    df = create_test_df()

    option = st.selectbox('Select year?', df['year'].unique())
    st.write('You selected: ', option)

    dict_years = {}
    for year in df['year'].unique():
        dict_years[year] = generate_map(df[df["year"] == year])

    folium_static(dict_years[option])
```
This code runs correctly:
![1](https://user-images.githubusercontent.com/20303036/89732686-bbba2980-da50-11ea-92e9-09125d562a0e.JPG)

I had tried to @st.cache functions with no positive results:
![Capture](https://user-images.githubusercontent.com/20303036/89733037-0a68c300-da53-11ea-89c9-f488247e5f66.JPG)

I understand that I must get deeper into advanced caching (https://docs.streamlit.io/en/stable/advanced_caching.html). Any guidelines about this are welcome.

**Comment by randyzwitch** [comment]
Hi @juancalvof - 

This is a misunderstanding on how `st.cache` works. `folium_static` can't be cached, because it doesn't return anything. It solely writes to the Streamlit app.

If you want to cache some part of the this app, you should apply `st.cache` to `generate_map`, which returns the Folium object back to Python.

**Comment by juancalvof** [comment]
Hi @randyzwitch !

Thanks. Yep. I understood that making the first tries, although I sent the snapshot error with `@st.cache` in `folium.static`.

Ok, Streamlit raises the same previous error because doesn’t know how to hash `folium.folium.Map`

so if a do this:
```
@st.cache (has_funcs={folium.folium.Map: hash_map()})
def generate_map(df):
...
```

What I need to define in the` hash_map()` function? 

**DOCUMENTATION:**
- https://docs.streamlit.io/en/stable/troubleshooting/caching_issues.html
- https://docs.streamlit.io/en/stable/advanced_caching.html

**Comment by randyzwitch** [comment]
Per https://github.com/randyzwitch/streamlit-folium/issues/4#issuecomment-672902328, there's nothing for Streamlit to cache.

**Comment by juancalvof** [comment]
Yep. I understood that, but I was referring to the option of caching Folium Maps. It this thread I understood you were going to check with your internal messageboard: https://discuss.streamlit.io/t/caching-folium-maps/5011/2

Maybe I should have write in the Streamlit discussion. My bad. Sorry. :sunglasses:

**Comment by randyzwitch** [comment]
Closing as `wontfix`. The new `st.experimental_memo` caches functions differently than `st.cache`, which may solve this issue. Otherwise, not sure how I could solve this as part of this package.

**Comment by kevinlinxc** [comment]
st.experimental_memo doesn't seem to solve this, I get `TypeError: cannot pickle 'weakref' object`
