### ISSUE TITLE
st_folium map update after add_to(m)

### ISSUE THREAD

**Issue by teemuja** [randyzwitch/streamlit-folium#46]
Hi! Im trying to apply superior interactivity of st_folium module to get data on map according the screen bounds but the _original_ st_folium map wont show the added layer when the code reruns. Not sure if this is an issue at all or am I just doing something wrong here (still quite newbie in python&streamlit..). Something related to reruns? How could/should I workaround here? 🙏
See test & code: https://share.streamlit.io/teemuja/st_folium_test/main/app1.py

**Comment by teemuja** [comment]
Well probably doable with session_state way so this was more "lack-of-streamlit-know-how -issue" than an issue for st_folium.. Will close this.

**Comment by sfc-gh-zblackwood** [comment]
Agreed. Definitely doable with session_state.
