### ISSUE TITLE
Map flickering

### ISSUE THREAD

**Issue by giswqs** [randyzwitch/streamlit-folium#53]
I am trying to add some [Google Earth Engine](https://earthengine.google.com/) layers (XYZ tile layers) to the map. You can see that the layers have been added successfully, but the map keeps refreshing. Any advice?

```python
import ee
import geemap.foliumap as geemap
import streamlit as st
from streamlit_folium import st_folium

m = geemap.Map()
dem = ee.Image("USGS/SRTMGL1_003")
m.addLayer(dem, {}, "DEM")
st_data = st_folium(m, width=1000)
```
![Peek 2022-05-07 22-25](https://user-images.githubusercontent.com/5016453/167279140-aa25f6c6-4ab8-4680-8c09-a3794988fee8.gif)

To test it in a notebook:
```python
import ee
import geemap.foliumap as geemap

m = geemap.Map()
dem = ee.Image("USGS/SRTMGL1_003")
m.addLayer(dem, {}, "DEM")
m
```

**Comment by giswqs** [comment]
This is the warning message that shows up briefly, then it disappears and the map keep flickering. 

![image](https://user-images.githubusercontent.com/5016453/167279252-e255adc8-1b68-4bbd-9129-05e230704bac.png)

**Comment by randyzwitch** [comment]
Hi @giswqs - 

I don't _know_ that this has been fixed, but @blackary made a few updates this morning for unrelated things. So can you try to update to 0.6.9 and see if anything improved?

Best,
Randy

**Comment by giswqs** [comment]
I just tested v0.6.9. The issue persists.

**Comment by giswqs** [comment]
Here is the web app that can demonstrate the issue. 

https://share.streamlit.io/giswqs/geospatial-apps/apps/flickering.py
https://github.com/giswqs/geospatial-apps/blob/master/apps/flickering.py

**Comment by danlessa** [comment]
I confirm the same issue on streamlit=1.9.0, streamlit-folium=0.6.10, folium=0.12.1.post1

**Comment by KassiusKlay** [comment]
Having same issue as @danlessa on Safari

**Comment by danlessa** [comment]
From what I did investigate, this flickering happens only when adding a new layer or basemap with `geemap`

Also, it is associated with the `index.tsx` script calling `Streamlit.setComponentValue` every time that Streamlit sends an `RENDER_EVENT` to the frontend. `__GLOBAL_DATA__` never gets written for some reason. As a result, an infinite loop is generated, as `onRender`triggers the `setComponentValue` which makes Streamlit re-run, therefore triggering `onRender`.

Deactivating that line: https://github.com/randyzwitch/streamlit-folium/blob/dfbc4434a6637bf70e7c88d8ef3e5762333866a7/streamlit_folium/frontend/src/index.tsx#L153 partially mitigates the issue, wit

**Comment by giswqs** [comment]
@danlessa Thank you for looking into this. I am no JavaScript expert. What file should we modify to test this? The folder structure of the package installed on a computer does not have the `src` directory as this GitHub shows. 

![image](https://user-images.githubusercontent.com/5016453/169195786-5475fdc0-1fd3-4ba5-b10f-0537f81786bc.png)

**Comment by giswqs** [comment]
Any updates on solving this bug? This map flicking issue makes the package unusable for any Earth Engine web apps.

**Comment by randyzwitch** [comment]
0.6.11 will be on PyPI as soon as the GitHub action completes...please take a look and let us know if you're still seeing any weirdness!

**Comment by danlessa** [comment]
I confirm that the issue is fixed. Many thanks for the effort!

**Comment by giswqs** [comment]
I can also confirm that the issue has been resolved. Thank you very much.
