### ISSUE TITLE
Returning Latitude, Longitude values from folium map on mouse click to python script (streamlit webapp)

### ISSUE THREAD

**Issue by hasantanvir79** [randyzwitch/streamlit-folium#6]
I am writing a webapp where the user will click on the map and the latitude, longitude will be returned to the python script. the webapp is written on streamlit and for the map I am using folium. Currently, I used folium.LatLngPopup() to get the on click lat long of the clicked location, but I am very confused how to retrieve the values in my python script for further processing.  

This is how it looks currently:

[![This is how it looks currently][1]][1]

#code snippet

    import streamlit as st
    from streamlit_folium import folium_static
    import folium
    m = folium.Map()
    m.add_child(folium.LatLngPopup())
    folium_static(m)

  [1]: https://i.stack.imgur.com/gRnI9.png

There might not be a native solution to it but any workaround will be appreciated!

**Comment by randyzwitch** [comment]
Thanks for opening the issue.

Does Folium return this value back when you use in a Jupyter Notebook? I'm trying to understand whether it's Python or JavaScript that is creating this value.

**Comment by hasantanvir79** [comment]
> Thanks for opening the issue.
> 
> Does Folium return this value back when you use in a Jupyter Notebook? I'm trying to understand whether it's Python or JavaScript that is creating this value.

No, it's part of a streamlit webapp, the script is in app.py and I am simply running the app.py in a terminal 
`streamlit run app.py`
running on localhost. I hope that helps!

**Comment by randyzwitch** [comment]
Yes, I understand you are making a Streamlit app. What I'm asking is whether the ability to return the lat/lon values is present in the Python Folium library itself. 

This package right now is a very small wrapper (5 lines of code) to take the output of Folium and display it. If Folium doesn't have a method to get the lat/lon values, then this stops being a "Folium" problem and becomes writing custom functionality.

**Comment by hasantanvir79** [comment]
> Yes, I understand you are making a Streamlit app. What I'm asking is whether the ability to return the lat/lon values is present in the Python Folium library itself.
> 
> This package right now is a very small wrapper (5 lines of code) to take the output of Folium and display it. If Folium doesn't have a method to get the lat/lon values, then this stops being a "Folium" problem and becomes writing custom functionality.

No it is not possible to return lat/lon values from folium package itself as far as I have known. the only functionality it provides is through this class LatLngPopup() available in https://github.com/python-visualization/folium/blob/master/folium/features.py

**Comment by hasantanvir79** [comment]
Hey @andfanilo thank you very very much! It helped a big time :+1:

**Comment by spinvettle** [comment]
Does anyone know how to print latitude and longitude in the console？

**Comment by randyzwitch** [comment]
Version 0.6.0 is now on PyPI. Use `pip install -U streamlit-folium` to get the latest version. Please also see the release notes on how this version is believed to solve this issue

https://github.com/randyzwitch/streamlit-folium/releases/tag/v0.6.0
