### ISSUE TITLE
Responsive view

### ISSUE THREAD

**Issue by banjtheman** [randyzwitch/streamlit-folium#7]
Hey, thanks for getting this component up and working. One thing I noticed was that on mobile the map always takes up 700px for the width column, which causes an ugly scroll bar to appear. To fix this I had to hardcode a style into the Streamlit app.
Not sure if this is for all components or just this one, but will just point it out here. 

```
make_map_responsive= """
 <style>
 [title~="st.iframe"] { width: 100%}
 </style>
"""
st.markdown(make_map_responsive, unsafe_allow_html=True)
```

**Comment by randyzwitch** [comment]
Thanks. This is probably one of those edge cases whether it belongs here or part of the design of Streamlit components. To give flexibility to users to set their size, I pass through width and height to the components functions:

https://github.com/randyzwitch/streamlit-folium/blob/master/streamlit_folium/__init__.py#L78

But if you want to make the size dynamic, it's not something we currently provide.

**Comment by ldmtwo** [comment]
That was driving me crazy. In my case, I couldn't make the map larger. Could just be user error, but this hack worked. Thanks @banj

**Comment by jbvsmo** [comment]
@randyzwitch The normal map from streamlit has a button for full screen, which just gives a bigger area for it to use.
Can't you always use the width/height as 100% of the container like @banjtheman suggested?

Having the map full screen would be really important for desktop applications

**Comment by giswqs** [comment]
It would be nice if the folium map can automatically take up 100% width of the page, just like the streamlit width when setting `st.set_page_config(layout="wide")`

![image](https://user-images.githubusercontent.com/5016453/128617708-9d3bbeb8-1f3a-4fe6-b44d-50c423ec0f52.png)

**Comment by JurijsNazarovs** [comment]
@banjtheman, unfortunately that hack does not work for me. I plot the map as 
```python3
from streamlit_folium import st_folium
import streamlit as st
import folium

st.set_page_config(layout="wide")
make_map_responsive = """
     <style>
     [title~="st.iframe"] { width: 100%}
     </style>
    """
st.markdown(make_map_responsive, unsafe_allow_html=True)
left, right = st.columns([1, 1])
with left:
    st.text_input("Write something")
    m = folium.Map(location=(0, 0), zoom_start=20)
    map_output = st_folium(
        m,
        #width=900,
        #height=900,
        returned_objects=["last_object_clicked"])
```

What do I do wrong?

**Comment by banjtheman** [comment]
Seems it doesn’t work with columns 
https://github.com/randyzwitch/streamlit-folium/issues/7#issuecomment-942000418

**Comment by woosal1337** [comment]
> I used the hack provided by @banjtheman. It works like a charm. See https://streamlit.gishub.org
> 
> ![](https://camo.githubusercontent.com/60ddfcce83e7ec0739865517fba3a24df0a48ee72c8757633d0bbcf634b29155/68747470733a2f2f692e696d6775722e636f6d2f544e56754664632e676966) [ ![68747470733a2f2f692e696d6775722e636f6d2f544e56754664632e676966](https://camo.githubusercontent.com/60ddfcce83e7ec0739865517fba3a24df0a48ee72c8757633d0bbcf634b29155/68747470733a2f2f692e696d6775722e636f6d2f544e56754664632e676966) ](https://camo.githubusercontent.com/60ddfcce83e7ec0739865517fba3a24df0a48ee72c8757633d0bbcf634b29155/68747470733a2f2f692e696d6775722e636f6d2f544e56754664632e676966) [ ](https://camo.githubusercontent.com/60ddfcce83e7ec0739865517fba3a24df0a48ee72c8757633d0bbcf634b29155/68747470733a2f2f692e696d6775722e636f6d2f544e56754664632e676966)

Any update on this?
