### ISSUE TITLE
Assign map width as percentage in st_folium

### ISSUE THREAD

**Issue by junjiez** [randyzwitch/streamlit-folium#71]
Hi there, I am wondering is it possible to assign the map width as percentage in st_folium? If this option is not offered, why? 

Not an expert in streamlit component yet. Could anybody explain the reason behind that? Thanks!

**Comment by SpencerMartel** [comment]
This is somewhat a streamlit problem and general responsive design in streamlit problem. You can track the issue [here].(https://github.com/streamlit/streamlit/issues/708)
