### ISSUE TITLE
Question ? is it possible to redraw the same map

### ISSUE THREAD

**Issue by djouallah** [randyzwitch/streamlit-folium#75]
Thanks for component.
I got the map to work and got the last click coordinates working just fine, then I use those coordinates to Query a database that return some points next to the point, it work very well, my Question is there a way to redraw the same map using these new data, currently the only way I can see is to create another map, which is not very convinient

thanks again
cheers

**Comment by randyzwitch** [comment]
From a convenience perspective, the map gets re-drawn each time based on the Streamlit execution model. Meaning, as you are passing the data from Folium back to Streamlit, the query can then run and change the map. You can see this with the National Parks example:

https://github.com/randyzwitch/streamlit-folium/blob/master/examples/interactive_app.py

As you're moving the map, the bounding box changes, which changes what points are shown. If you click on a point, that information is brought back to Streamlit, then you can act upon it.

Another example would be this app:

https://github.com/randyzwitch/streamlit-folium-snowflake-openstreetmap/blob/main/streamlit_app.py

As you interact, the map gets re-drawn each time, but with session state, the data becomes available between each run. So the top-down flow gets maintained.

Does this sound like what you are talking about @djouallah?

**Comment by djouallah** [comment]
Thanks, I guess I need to read more about session state :)
