### ISSUE TITLE
How to feed click-data from Python back to map

### ISSUE THREAD

**Issue by lurifaxel** [randyzwitch/streamlit-folium#88]
Hi!

Thanks for creating this plugin, you rock! :) 

I'm new to both Streamlit and Folium and may be missing something fundamental here, but I can't seem to feed the data returned from click events back to the map! My use case is simple: center the map on the coordinate where the user clicked!

Creating the map as per the [bi-directional data example](https://randyzwitch-streamlit-folium-examplesstreamlit-app-qc22uj.streamlit.app/) works and I can see the data returned from clicks in `st_data`. 

I've tried to zoom the map by setting the map bounds with `m.fit_bounds`, using the click event coordinates plus arbitrary deltas like so:  `m.fit_bounds(bounds=[st_data["last_clicked"]["lat"] - 0.001, st_data["last_clicked"]["lng"] - 0.001], padding=5, max_zoom=20)`. This seems to do nothing.

I have also tried setting data from `st_data` in the session state and use the session_state vars for initializing the map, hoping it would re-render, but to no avail.

What's the recommended way to do this? Or am I missing something and this is not supported?

**Comment by blackary** [comment]
Hi @lurifaxel,

One way to accomplish this with session_state is like this:

```python
import streamlit as st
from streamlit_folium import st_folium

if "map_center" not in st.session_state:
    st.session_state.map_center = {"lat": 39.94, "lng": -75.16}

# Note that last_clicked returns a dictionary, and folium.Map expects a list of coordinates
map = folium.Map(list(st.session_state.map_center.values()), zoom_start=16)

output = st_folium(map, width=700, height=500)

if (
    output["last_clicked"] is not None
    and output["last_clicked"] != st.session_state.map_center
):
    st.session_state.map_center = output["last_clicked"]
    st.experimental_rerun()
```

Does that work for your use-case?

**Comment by lurifaxel** [comment]
Thank you for helping out, much appreciated! :)

Yeah, that does work! The `st.experimental_rerun()` was kind of the missing link. I got it to work reasonably well by using a button too, which also triggers re-rendering, and works pretty well with my use case (configure settings, then re-render the map).

In a perfect world, it would be nice to be able to adjust the map location and markers without re-rendering the map (which is slightly visually jarring), but I suppose that's not the world we live in?

**Comment by blackary** [comment]
@lurifaxel Yeah, that would be ideal, but I don't have a good idea about how to accomplish that right now. Definitely would be a nice improvement!
