### ISSUE TITLE
float-container

### ISSUE THREAD

**Issue by kmedri** [randyzwitch/streamlit-folium#93]
Hi,

I am having trouble rendering the folium map in the width of the folium app.
I see in the iframe there is a div with the class "float-container" containing two div's with class "float-child":

```
<div class="float-container">
    <div class="float-child">
        <div id="map_div" class="leaflet-container leaflet-touch leaflet-fade-anim leaflet-grab leaflet-touch-drag leaflet-touch-zoom" tabindex="0" style="height: 700px; width: 725px; position: relative; outline: none;"> # I have removed the contents of this div to reduce the code
        </div>
    </div>
    <div class="float-child">
        <div id="map_div2" style="height: 700px; width: 725px;">
        </div>
    </div>
</div>
```
```
.float-child {
    width: 50%;
    float: left;
}
```

It appears that these two div's CSS is overwitten by `<div id="map_divstyle="height: 700px; width: 725px;">"` and  `<div id="map_div2"style="height: 700px; width: 725px;">` which is from:

`st_data = st_folium(m, width=725)`

If we could only have one column <div class="float-container"> and not have the two div's with class "float-child", and rely on Streamlit's column structure if we need more than one column, we would not need to rely on widths?

Sorry I am a bit of a newbie to Streamlit.

Is this a Streamlit issue?
Is there a workaround?

**Comment by Berhinj** [comment]
Hah I posted the exact same issue yesterday, I've got a temporary solution (which could mess with DualMap but I don't use them much). So I cloned the repo, 

in streamlit_folium/frontend/public/index.html, replaced this

```
<div class="float-container">
    <div class="float-child">
        <div id="map_div"></div>
    </div>
    <div class="float-child">
        <div id="map_div2"></div>
    </div>
</div>
```
by this

```
<div class="float-container">
  <div class="float-child">
    <div id="map_div"></div>
  </div>
```

 if you want to have a dynamic width you need to do 
`st_data = st_folium(m, width=None)`

Note there are some installation that are handled in the github workflow (.github/workflows/run_tests_each_PR.yml) that you'll need to make sure they happen. In my case I just wanted it to run locally so I've just ran them manually

```
cd streamlit_folium/frontend/
npm install
npm run build
```

Here is how it looks (note, I've removed the borders to make it wider)

https://user-images.githubusercontent.com/34525099/202417786-1246dab3-f417-467e-9dce-da07b5523fec.mp4

**Comment by kmedri** [comment]
That is a great fix, I think for now I will stick with the status quo as I do not want to manage a forked repo :-)
Thank you for your time, I will add this to a local repo though to try it out.

**Comment by blackary** [comment]
Hi @kmedri, thanks for reporting the issue! Can you give me a specific example where the current html structure is an issue? I recognize that it's a bit strange, but it exists to support DualMaps (which may not be very commonly used). If you could share an example of some code, and what you expect it to do, and what it's not doing because of the two float-child objects, that would be very helpful. I can certainly believe it's causing issues, I'm just not totally understanding what the issue is.
