### ISSUE TITLE
Error when I try to add plugins.FloatImage with st_folium

### ISSUE THREAD

**Issue by cwerner** [randyzwitch/streamlit-folium#94]
Hi :wave:

... and thanks for providing this great addition to `streamlit`. 

I was wondering: are `folium.plugins` generally supported? I wanted to add a `FloatImage` to the canvas (using `st_folium`) but I get an error:

```
.../lib/python3.11/site-packages/streamlit_folium/__init__.py", line 242, in generate_leaflet_string
    leaflet = m._template.module.script(m)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TemplateModule' object has no attribute 'script'
```

I see there's some special magic for the DualMap plugins - so maybe the FloatImage requires some special treatment, too?

I'm using python 3.11 and streamlit-folium 0.7

Cheers,
C

**Comment by randyzwitch** [comment]
This is a pretty old issue, but I bet it's fixed with our newest release, as we've improved how we load the folium dependencies. Closing, but if you're still interested and it's not fixed, happy to re-open
