### ISSUE TITLE
Legend of the map is not displayed

### ISSUE THREAD

**Issue by MatheusLevy** [randyzwitch/streamlit-folium#95]
The legend of my map is not displayed using the st_folium when colorbar= false. The code:
```
import pandas as pd
import folium
import geopandas as gpd
import numpy as np
import mapclassify
import streamlit as st
from streamlit_folium import st_folium

url = ("https://raw.githubusercontent.com/python-visualization/folium/master/examples/data")
state_geo = f"{url}/us-states.json"
state_unemployment = f"{url}/US_Unemployment_Oct2012.csv"

state_unemployment = pd.read_csv(state_unemployment)
geoJSON_df = gpd.read_file(state_geo)

geoJSON_df.rename(columns={'id': 'State'}, inplace=True)

gdf = state_unemployment.merge(geoJSON_df, on='State', how='left')
gdf = gpd.GeoDataFrame(gdf)

bins = mapclassify.Quantiles(gdf['Unemployment'], k=5).bins
choropleth = gdf.explore(
    column='Unemployment',
    scheme='UserDefined',
    classification_kwds=dict(bins=bins),
    legend=True,
    legend_kwds=dict(colorbar=False),
)

st_folium(choropleth, width=700,height=500)
```

Displayed:
![displayed](https://user-images.githubusercontent.com/48130978/202729863-6779a556-b2c8-40a4-b78d-d5e4e18b1df4.png)

Expected:
![expected](https://user-images.githubusercontent.com/48130978/202729098-599db9ee-01d7-4cbd-8309-823fb72aaaaf.png)

**Comment by romanzdk** [comment]
I have the same issue. I hacked it this way - https://discuss.streamlit.io/t/ann-streamlit-folium-a-component-for-rendering-folium-maps/4367/22

**Comment by MatheusLevy** [comment]
I done this, it worked with the folium_static, but not with the st_folium. My solution was to display the legend as a component apart from the map component. I sync the colors from the map and the legend by passing a custom list of colors for the map. So the map stayed the same.
